### ISSUE TITLE
lack of sample_multistep function

### ISSUE THREAD

**Issue by quantumiracle** [mbreuss/consistency_trajectory_models_toy_task#1]
Hi,

Thanks for you great contribution to this repo. However, I found a missing function of `model.sample_multistep` as line:
https://github.com/mbreuss/consistency_trajectory_models_toy_task/blob/a6eb9ebbc657bd66d15e6c1771133dbbab31c97e/ctm/visualization/vis_utils.py#L34

Is it left out in any commit? 

Thanks

**Comment by mbreuss** [comment]
Hi, 

thanks for the interest in this codebase. I didn't finish the implementation of the new multistep sampling method introduced in the paper, as I was mainly interested in the single-step behavior of CTM. Feel free to add it, that would be interesting to try out.

Btw, I like your paper about consistency models in RL. I struggled a bit to make them work on this toy task in another repo: https://github.com/mbreuss/consistency_models_toy_task . Can you share some insights, what made the training and results stable for your application?

**Comment by quantumiracle** [comment]
Hi, 

Thanks for your quick response. 

For consistency model implementation, I think the best ways are (1). to check official implementation by OpenAI (https://github.com/openai/consistency_models) function by function; and (2) try Improved Techniques for Consistency Models (https://openreview.net/forum?id=WNzy9bRDvG). In my consistency for RL code, I take a minimal implementation of it (https://github.com/quantumiracle/Consistency_Model_For_Reinforcement_Learning/blob/master/agents/consistency.py) for simplicity, however with several small differences from official implementation (which I found not affecting the offline RL performances significantly) like:

1. https://github.com/openai/consistency_models/blob/6d26080c58244555c031dbc63080c0961af74200/cm/karras_diffusion.py#L346

2. the usage of heun_solver for loss calculation (https://github.com/openai/consistency_models/blob/6d26080c58244555c031dbc63080c0961af74200/cm/karras_diffusion.py#L143), which I found it should be equivalent to my implementation.

One trick I found essential in offline RL setting is the scaling of consistency loss (https://github.com/quantumiracle/Consistency_Model_For_Reinforcement_Learning/blob/4f12652fa8ad03a798ff4400c9f7e21e0c650cf5/agents/ql_consistency.py#L326), since in offline RL it needs to balance the scales of consistency loss and a behavior cloning loss. This may also be true with consistency training only since it is also proposed in Improved Techniques paper.

**Comment by mbreuss** [comment]
Thank you for all the tips! I guess I will give it another shot if I have the time. Did you try out the improved techniques already for the RL setting? If so,  do they improve the stability of the RL setting?

**Comment by quantumiracle** [comment]
Back to the CTM implementation, I'm trying to replicate your results shown in readme, but I got CTM loss\~0.008, Dffusion loss\~0.92, Euler sample and onestep sample as following:
![cm_euler_epochs_2000](https://github.com/mbreuss/consistency_trajectory_models_toy_task/assets/22659010/1b88072a-99e5-4cc8-8fbb-eadf11735561)
![cm_onestep_epochs_2000](https://github.com/mbreuss/consistency_trajectory_models_toy_task/assets/22659010/8856ca52-434f-4c3d-bf61-73c80825f99b)
with 2000 epochs, lr=1e-3, use_pretraining=False for training.

Not sure if this matches your results (seems a bit worse) since I found you've changed the implementation a bit after uploading the initial results.

Thanks for any help in advance!

**Comment by mbreuss** [comment]
I have some deadline on saturday, I can come back this next week and will give you an update!

**Comment by quantumiracle** [comment]
> Thank you for all the tips! I guess I will give it another shot if I have the time. Did you try out the improved techniques already for the RL setting? If so, do they improve the stability of the RL setting?

I actually tried all that can be used in my implementation (with argument improved_CT https://github.com/quantumiracle/Consistency_Model_For_Reinforcement_Learning/blob/4f12652fa8ad03a798ff4400c9f7e21e0c650cf5/agents/ql_consistency.py#L188) but found it less significant in offline RL setting (no statistically significant improvement). However, this can also attribute to the complexity of offline RL dataset and setting. Your toy example  should produce more obvious difference if those are useful I think.

**Comment by quantumiracle** [comment]
> I have some deadline on saturday, I can come back this next week and will give you an update!

Sure, take your time!

**Comment by mbreuss** [comment]
@quantumiracle sorry for the late reply. 
So your assumptions were right, I played with the diffusion noise parameters a lot after uploading the initial images and choose suboptimal ones. I tested them again and changed them to better ones, I hope it works better now! The distillation script is now also improved, as it also contained several bugs. Let me know if you have other questions!

**Comment by quantumiracle** [comment]
Thanks for the update!

Indeed the performance is better for 2D case with `sigma_max=1`. However, I also found mode collapse when `sigma_max=5` with one-step generation.

**Comment by mbreuss** [comment]
I had similar issues. So far I was not able to make single step prediction work consistently. If you find anything to improve it, feel free to change the code. However, in the openreview section of the new consistency model paper, the authors mention, that these models work better in high dimensional cases but struggle in 1D problems, so maybe that's the case. Although I don't know why this should be the case. https://openreview.net/forum?id=WNzy9bRDvG

**Comment by quantumiracle** [comment]
I see. 

Also, I've forked from your repo and made some modifications to support Cifar10 and Imagenet64 [here](https://github.com/quantumiracle/Consistency-Trajectory-Model), by merging the network architecture of original CTM repo. See if you are interested in also debugging the code for these large datasets.

**Comment by mbreuss** [comment]
Ah very cool, when I have some time, I will try it out! Thanks for sharing.
