### ISSUE TITLE
[Not an issue] Thank you for being interested in CTM!

### ISSUE THREAD

**Issue by ChiehHsinJesseLai** [mbreuss/consistency_trajectory_models_toy_task#2]
Hello, 

Thank you for being interested in our work and having this wonderful implementation of CTM!
Perhaps you'd also be interested in our code https://github.com/sony/ctm.

Chieh-Hsin (and on behalf of Dongjun Kim)

**Comment by mbreuss** [comment]
Hi,

thank you for coming up with the model and the paper! 
Thanks for sharing the link, I added it to the readme, so other people can also find it from here. 
Let me know if you spot any mistakes I made in this implementation.

**Comment by ChiehHsinJesseLai** [comment]
Hi, 

Thank you very much!
Really like your implementation : )
